### ISSUE TITLE
Indent based on sibling

### ISSUE THREAD

**Issue by bholtbholt** [bholtbholt/passages#2]
```css

/*
  This sibling selector might be released in Tailwind 3
  https://tailwindcss.com/docs/just-in-time-mode#sibling-selector-variants
*/
.peer\:indent-6 + .peer\:indent-6 {
  text-indent: 1.5rem;
}

```
